vim.g.gruvbox_bold = 1
vim.g.gruvbox_italic = 1
vim.g.gruvbox_transparent_bg = 0
vim.g.gruvbox_underline = 0
vim.g.gruvbox_undercurl = 0
vim.g.gruvbox_termcolors = 256
vim.g.gruvbox_contrast_light = "hard"
vim.g.gruvbox_contrast_dark = "hard"
vim.g.gruvbox_hls_cursor = "orange"
vim.g.gruvbox_color_column = "bg1"
vim.g.gruvbox_vert_split = "bg0"
vim.g.gruvbox_italicize_comments = 1
vim.g.gruvbox_italicize_strings = 0
vim.g.gruvbox_invert_selection = 0
vim.g.gruvbox_invert_signs = 0 -- Inverts GitGutter and Syntastic signs
vim.g.gruvbox_invert_indent_guides = 0
vim.g.gruvbox_invert_tabline = 1
vim.g.gruvbox_improved_strings = 0
vim.g.gruvbox_improved_warnings = 0
-- vim.g.gruvbox_number_column = "none"
-- vim.g.gruvbox_sign_column = "none"
-- vim.cmd([[highlight CursorLineNR guibg=NONE]])
-- vim.cmd([[highlight Normal guibg=NONE ctermfg=NONE]])
-- vim.cmd([[highlight LineNr guifg=#5EACD3]])
