vim.g.gruvbox_material_palette = "original" -- `material`, `mix`, `original`
vim.g.gruvbox_material_background = "hard" -- 'hard', 'medium', 'soft'
vim.g.gruvbox_material_foreground = "original" -- `material`, `mix`, `original`
vim.g.gruvbox_material_enable_italic = 1
vim.g.gruvbox_material_enable_bold = 1
vim.g.gruvbox_material_transparent_background = 0
vim.g.gruvbox_material_visual = "reverse" -- 'green|blue|red background', 'reverse'
vim.g.gruvbox_material_sign_column_background = "default" -- 'none'
vim.g.gruvbox_material_spell_foreground = "colored"
vim.g.gruvbox_material_ui_contrast = "high" -- 'low', 'high'
vim.g.gruvbox_material_show_eob = 0
vim.g.gruvbox_material_diagnostic_text_highlight = 1 -- for error/warning/info/hint texts
vim.g.gruvbox_material_diagnostic_line_highlight = 1 -- for error/warning/info/hint lines
vim.g.gruvbox_material_diagnostic_virtual_text = "colored" -- 'grey', 'colored'
vim.g.gruvbox_material_statusline_style = "original" -- 'default', 'mix', 'original'
vim.g.gruvbox_material_better_performance = 1 -- This feature allows you to load part of the code on demand by placing them in the `after/syntax` directory.
-- vim.cmd([[ highlight CursorLineNR guibg=none]])
-- vim.cmd([[ highlight LineNr guifg=#5EACD3]])
